admin_index:
    path:     /
    defaults: { _controller: "HZraumReservierungBundle:Student:index" }
    methods:  GET

admin_show:
    path:     /{id}/show
    defaults: { _controller: "HZraumReservierungBundle:Student:show" }
    methods:  GET

admin_new:
    path:     /new
    defaults: { _controller: "HZraumReservierungBundle:Student:new" }
    methods:  [GET, POST]

admin_edit:
    path:     /{id}/edit
    defaults: { _controller: "HZraumReservierungBundle:Student:edit" }
    methods:  [GET, POST]

admin_delete:
    path:     /{id}/delete
    defaults: { _controller: "HZraumReservierungBundle:Student:delete" }
    methods:  DELETE
