<?php

namespace HZ\raumReservierungBundle\Repository;

/**
 * RaumRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RaumRepository extends \Doctrine\ORM\EntityRepository
{
}
